FoodMenuApp/FoodMenuApp/FoodMenuApp/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register, name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FoodMenuApp/FoodMenuApp/food/urls.py
from django.urls import path
from . import views

app_name ='food'
urlpatterns = [
    #/food/
    path('',views.IndexClassView.as_view(), name='index'),
    #/food/items/
    path('items/',views.item, name='item'),
    #/food/1
    path('<int:pk>',views.FoodDetail.as_view(),name='detail'),
    path('add/',views.CreateItem.as_view(),name='create_item'),
    path('update/<int:id>',views.update_item, name='update_item'),
    path('delete/<int:id>',views.delete_item, name='delete_item'),
]

FoodMenuApp/FoodMenuApp/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=100)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=1000, default="https://in.images.search.yahoo.com/images/view;_ylt=AwrPrWs.BGlnyCQbl1a9HAx.;_ylu=c2VjA3NyBHNsawNpbWcEb2lkA2JhNGE3ZTJkM2YyZTlmNTM3NjExNmQ2MTU0YzRkNzk1BGdwb3MDNDAEaXQDYmluZw--?back=https%3A%2F%2Fin.images.search.yahoo.com%2Fsearch%2Fimages%3Fp%3Dfood%2Bplaceholder%2Bimage%2Bcoming%2Bsoon%26ei%3DUTF-8%26type%3DE211IN1274G0%26fr%3Dmcafee%26fr2%3Dp%253As%252Cv%253Ai%252Cm%253Asb-top%26tab%3Dorganic%26ri%3D40&w=600&h=600&imgurl=www.food4fuel.com%2Fwp-content%2Fuploads%2Fwoocommerce-placeholder-600x600.png&rurl=https%3A%2F%2Fwww.food4fuel.com%2Fproduct%2F5-family-packs-6-servings%2F&size=22KB&p=food+placeholder+image+coming+soon&oid=ba4a7e2d3f2e9f5376116d6154c4d795&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&fr=mcafee&tt=5+family+packs+-+6+servings+-+Food+4+Fuel+-+Healthy+Meal+Plans+Crafted+...&b=0&ni=250&no=40&ts=&tab=organic&sigr=O6TCINlGWKie&sigb=C7SkDQUYJkC9&sigi=K2eEMsWUqFAp&sigt=TqOOw8YGv.3v&.crumb=8pexUTu/CHY&fr=mcafee&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&type=E211IN1274G0")
    
    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

FoodMenuApp/FoodMenuApp/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username
    

FoodMenuApp/FoodMenuApp/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

FoodMenuApp/FoodMenuApp/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

FoodMenuApp/FoodMenuApp/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    template = loader.get_template('food\index.html')
    context = {
        'item_list':item_list,
    }
    return render(request, 'food/index.html',context)


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name ='item_list'
    


def item(request):
    return HttpResponse("This is an item view")

def detail_view(request, item_id):
    try:
        item_data = Item.objects.get(pk=item_id)
        context = {
            'item':item_data
        }
        return render(request,'food\detail.html',context)
    except Exception as e:
        return 

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'
     
def create_item(request):
   form = ItemForm(request.POST or None)
   if form.is_valid():
       form.save()
       return redirect('food:index')
   return render(request, 'food/item-form.html',{'form':form})

# class based view for create Item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'
    
    def form_valid(self, form):
        # To get the user who has currently logged in
        form.instance.user_name = self.request.user
        return super().form_valid(form)
    
    
def update_item(request, id):
    item = Item.objects.get(pk=id)
    form = ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food\item-form.html',{'form':form,'item':item})

def delete_item(request, id):
    item = Item.objects.get(id=id)
    
    if request.method == "POST":
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})

FoodMenuApp/FoodMenuApp/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created.')
            form.save()
            return redirect('login')
    else:    
        form = RegisterForm()
    return render(request, 'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

FoodMenuApp/FoodMenuApp/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static  'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <a href="#" class="navbar-brand">FoodApp</a>
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:create_item' %}">AddItem</a>
            <a class="nav-item nav-link" href="#">DeleteItem</a>
            <a class="nav-item nav-link" href="#">ViewItem</a>
            <a class="nav-item nav-link" href="#">EditItem</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
            
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

FoodMenuApp/FoodMenuApp/food/templates/food/detail.html
{% extends 'food\base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{object.item_image}}" class="card" height="200px" width="200px"/>
        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
        <h2>{{object.item_desc}}</h2>
        <h3>${{object.item_price}}</h3>
        <a href="{% url 'food:delete_item' object.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

FoodMenuApp/FoodMenuApp/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
</head>
<body>
    {% block body %}
        {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="100px" width="150px" src="{{item.item_image}}">
            </div>
            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6>${{item.item_price}}</h6>
                <h6>{{item.user_name}}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>

        
        {% endfor %}
        {% endblock %}
   
</body>
</html>

FoodMenuApp/FoodMenuApp/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2> Are you sure you want to delet {{item.item_name}}?</h2>
    <button type="submit">Confirm</button>
</form>

FoodMenuApp/FoodMenuApp/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        AddItem
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn-info" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

FoodMenuApp/FoodMenuApp/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{field.name}}
                                    {{field}}
                                </div>
                            {% endfor %}
                            <button class="btn-info" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

FoodMenuApp/FoodMenuApp/users/templates/users/logout.html
<h1> You have been logged out!! </h1>

FoodMenuApp/FoodMenuApp/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width='100px' height='100px' src="{{user.profile.image.url}}"/>

FoodMenuApp/FoodMenuApp/users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        REGISTER
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name}}
                                <br>
                                {{field}}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}